[[headers]]
  for = "/beta-app/WebGL/Build/*.data.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"
	
[[headers]]
  for = "/beta-app/WebGL/Build/*.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"

[[headers]]                                                                      
  for = "/beta-app/WebGL/Build/*.js"                                                             
  [headers.values]
    Content-Encoding = "js"
    Content-Type = "application/javascript"
	
[[headers]]                                                                      
  for = "/beta-app/WebGL/Build/*.js.br"                                                             
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"